package net.mcreator.jojowos.configuration;

import net.minecraftforge.common.ForgeConfigSpec;

public class SDCConfigFilesConfiguration {
	public static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();
	public static final ForgeConfigSpec SPEC;
	public static final ForgeConfigSpec.ConfigValue<String> CREATORNOTE1;
	public static final ForgeConfigSpec.ConfigValue<String> CREATORNOTE2;
	public static final ForgeConfigSpec.ConfigValue<String> CREATORNOTE3;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMSTRENGTH;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMDURABILITY;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMPRECISION;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMPOTENTIAL;
	public static final ForgeConfigSpec.ConfigValue<String> STARPLATINUMABILITY1;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY1COST;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY1CDMAX;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY1CDMIN;
	public static final ForgeConfigSpec.ConfigValue<String> STARPLATINUMABILITY2;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY2COST;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY2CDMAX;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY2CDMIN;
	public static final ForgeConfigSpec.ConfigValue<String> STARPLATINUMABILITY3;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY3COST;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY3CDMAX;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY3CDMIN;
	public static final ForgeConfigSpec.ConfigValue<String> STARPLATINUMABILITY4;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY4COST;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY4CDMAX;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY4CDMIN;
	public static final ForgeConfigSpec.ConfigValue<String> STARPLATINUMABILITY5;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY5COST;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY5CDMAX;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY5CDMIN;
	public static final ForgeConfigSpec.ConfigValue<String> STARPLATINUMABILITY6;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY6COST;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY6CDMAX;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY6CDMIN;
	public static final ForgeConfigSpec.ConfigValue<String> STARPLATINUMABILITY7;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY7COST;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY7CDMAX;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY7CDMIN;
	public static final ForgeConfigSpec.ConfigValue<String> STARPLATINUMABILITY8;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY8COST;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY8CDMAX;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY8CDMIN;
	public static final ForgeConfigSpec.ConfigValue<String> STARPLATINUMABILITY9;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY9COST;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY9CDMAX;
	public static final ForgeConfigSpec.ConfigValue<Double> STARPLATINUMABILITY9CDMIN;
	public static final ForgeConfigSpec.ConfigValue<Double> MAGICIANSREDSTRENGTH;
	public static final ForgeConfigSpec.ConfigValue<Double> MAGICIANSREDDURABILITY;
	public static final ForgeConfigSpec.ConfigValue<Double> MAGICIANSREDPRECISION;
	public static final ForgeConfigSpec.ConfigValue<Double> MAGICIANSREDPOTENTIAL;
	public static final ForgeConfigSpec.ConfigValue<Double> HIEROPHANTGREENSTRENGTH;
	public static final ForgeConfigSpec.ConfigValue<Double> HIEROPHANTGREENDURABILITY;
	public static final ForgeConfigSpec.ConfigValue<Double> HIEROPHANTGREENPRECISION;
	public static final ForgeConfigSpec.ConfigValue<Double> HIEROPHANTGREENPOTENTIAL;
	public static final ForgeConfigSpec.ConfigValue<Double> SILVERCHARIOTSTRENGTH;
	public static final ForgeConfigSpec.ConfigValue<Double> SILVERCHARIOTDURABILITY;
	public static final ForgeConfigSpec.ConfigValue<Double> SILVERCHARIOTPRECISION;
	public static final ForgeConfigSpec.ConfigValue<Double> SILVERCHARIOTPOTENTIAL;
	public static final ForgeConfigSpec.ConfigValue<Double> HERMITPURPLESTRENGTH;
	public static final ForgeConfigSpec.ConfigValue<Double> HERMITPURPLEDURABILITY;
	public static final ForgeConfigSpec.ConfigValue<Double> HERMITPURPLEPRECISION;
	public static final ForgeConfigSpec.ConfigValue<Double> HERMITPURPLEPOTENTIAL;
	public static final ForgeConfigSpec.ConfigValue<Double> THEFOOLSTRENGTH;
	public static final ForgeConfigSpec.ConfigValue<Double> THEFOOLDURABILITY;
	public static final ForgeConfigSpec.ConfigValue<Double> THEFOOLPRECISION;
	public static final ForgeConfigSpec.ConfigValue<Double> THEFOOLPOTENTIAL;
	public static final ForgeConfigSpec.ConfigValue<Double> THEWORLDSTRENGTH;
	public static final ForgeConfigSpec.ConfigValue<Double> THEWORLDDURABILITY;
	public static final ForgeConfigSpec.ConfigValue<Double> THEWORLDPRECISION;
	public static final ForgeConfigSpec.ConfigValue<Double> THEWORLDPOTENTIAL;
	static {
		BUILDER.push("Creator's Note");
		CREATORNOTE1 = BUILDER.define("Stand Stats", "Values over 100 may have unintend effects on gameplay.");
		CREATORNOTE2 = BUILDER.define("Stand Costs", "The cost of a skill within the skill tree.");
		CREATORNOTE3 = BUILDER.define("Stand Cooldowns", "Cooldowns are in ticks (Number/20 = Seconds)");
		BUILDER.pop();
		BUILDER.push("Star Platinum");
		STARPLATINUMSTRENGTH = BUILDER.comment("Increases the Power of your Stand's Moves (Default: 100)").define("Strength", (double) 100);
		STARPLATINUMDURABILITY = BUILDER.comment("Increases your Health, and Decreases Damage Taken (Default: 100)").define("Durability", (double) 100);
		STARPLATINUMPRECISION = BUILDER.comment("Increases the Effectiveness of your Stand's Moves (Default: 100)").define("Precision", (double) 100);
		STARPLATINUMPOTENTIAL = BUILDER.comment("Allows your Stand to Acquire More Moves and EXP (Default: 100)").define("Potential", (double) 100);
		STARPLATINUMABILITY1 = BUILDER.define("Ability 1", "Barrage");
		STARPLATINUMABILITY1COST = BUILDER.define("Ability 1 Cost", (double) 0);
		STARPLATINUMABILITY1CDMAX = BUILDER.define("Ability 1 Cooldown Max", (double) 400);
		STARPLATINUMABILITY1CDMIN = BUILDER.define("Ability 1 Cooldown Min", (double) 250);
		STARPLATINUMABILITY2 = BUILDER.define("Ability 2", "StarFinger");
		STARPLATINUMABILITY2COST = BUILDER.define("Ability 2 Cost", (double) 5);
		STARPLATINUMABILITY2CDMAX = BUILDER.define("Ability 2 Cooldown Max", (double) 400);
		STARPLATINUMABILITY2CDMIN = BUILDER.define("Ability 2 Cooldown Min", (double) 150);
		STARPLATINUMABILITY3 = BUILDER.define("Ability 3 ", "BearingShot");
		STARPLATINUMABILITY3COST = BUILDER.define("Ability 3 Cost", (double) 3);
		STARPLATINUMABILITY3CDMAX = BUILDER.define("Ability 3 Cooldown Max", (double) 200);
		STARPLATINUMABILITY3CDMIN = BUILDER.define("Ability 3 Cooldown Min", (double) 100);
		STARPLATINUMABILITY4 = BUILDER.define("Ability 4", "Inhale");
		STARPLATINUMABILITY4COST = BUILDER.define("Ability 4 Cost", (double) 3);
		STARPLATINUMABILITY4CDMAX = BUILDER.define("Ability 4 Cooldown Max", (double) 400);
		STARPLATINUMABILITY4CDMIN = BUILDER.define("Ability 4 Cooldown Min", (double) 150);
		STARPLATINUMABILITY5 = BUILDER.define("Ability 5", "TimeSkip");
		STARPLATINUMABILITY5COST = BUILDER.define("Ability 5 Cost", (double) 5);
		STARPLATINUMABILITY5CDMAX = BUILDER.define("Ability 5 Cooldown Max", (double) 500);
		STARPLATINUMABILITY5CDMIN = BUILDER.define("Ability 5 Cooldown Min", (double) 200);
		STARPLATINUMABILITY6 = BUILDER.define("Ability 6", "TimeStop");
		STARPLATINUMABILITY6COST = BUILDER.define("Ability 6 Cost", (double) 10);
		STARPLATINUMABILITY6CDMAX = BUILDER.define("Ability 6 Cooldown Max", (double) 2400);
		STARPLATINUMABILITY6CDMIN = BUILDER.define("Ability 6 Cooldown Min", (double) 1000);
		STARPLATINUMABILITY7 = BUILDER.define("Ability 7", "");
		STARPLATINUMABILITY7COST = BUILDER.define("Ability 7 Cost", (double) 0);
		STARPLATINUMABILITY7CDMAX = BUILDER.define("Ability 7 Cooldown Max", (double) 0);
		STARPLATINUMABILITY7CDMIN = BUILDER.define("Ability 7 Cooldown Min", (double) 0);
		STARPLATINUMABILITY8 = BUILDER.define("Ability 8", "");
		STARPLATINUMABILITY8COST = BUILDER.define("Ability 8 Cost", (double) 0);
		STARPLATINUMABILITY8CDMAX = BUILDER.define("Ability 8 Cooldown Max", (double) 0);
		STARPLATINUMABILITY8CDMIN = BUILDER.define("Ability 8 Cooldown Min", (double) 0);
		STARPLATINUMABILITY9 = BUILDER.define("Ability 9", "");
		STARPLATINUMABILITY9COST = BUILDER.define("Ability 9 Cost", (double) 0);
		STARPLATINUMABILITY9CDMAX = BUILDER.define("Ability 9 Cooldown Max", (double) 0);
		STARPLATINUMABILITY9CDMIN = BUILDER.define("Ability 9 Cooldown Min", (double) 0);
		BUILDER.pop();
		BUILDER.push("Magician's Red");
		MAGICIANSREDSTRENGTH = BUILDER.comment("Increases the Power of your Stand's Moves (Default: 80)").define("Strength", (double) 80);
		MAGICIANSREDDURABILITY = BUILDER.comment("Increases your Health, and Decreases Damage Taken (Default: 80)").define("Durability", (double) 80);
		MAGICIANSREDPRECISION = BUILDER.comment("Increases the Effectiveness of your Stand's Moves (Default: 60)").define("Precision", (double) 60);
		MAGICIANSREDPOTENTIAL = BUILDER.comment("Allows your Stand to Acquire More Moves and EXP (Default: 40)").define("Potential", (double) 40);
		BUILDER.pop();
		BUILDER.push("Hierophant Green");
		HIEROPHANTGREENSTRENGTH = BUILDER.comment("Increases the Power of your Stand's Moves (Default: 60)").define("Strength", (double) 60);
		HIEROPHANTGREENDURABILITY = BUILDER.comment("Increases your Health, and Decreases Damage Taken (Default: 80)").define("Durability", (double) 80);
		HIEROPHANTGREENPRECISION = BUILDER.comment("Increases the Effectiveness of your Stand's Moves (Default: 60)").define("Precision", (double) 60);
		HIEROPHANTGREENPOTENTIAL = BUILDER.comment("Allows your Stand to Acquire More Moves and EXP (Default: 40)").define("Potential", (double) 40);
		BUILDER.pop();
		BUILDER.push("Silver Chariot");
		SILVERCHARIOTSTRENGTH = BUILDER.comment("Increases the Power of your Stand's Moves (Default: 60)").define("Strength", (double) 60);
		SILVERCHARIOTDURABILITY = BUILDER.comment("Increases your Health, and Decreases Damage Taken (Default: 80)").define("Durability", (double) 80);
		SILVERCHARIOTPRECISION = BUILDER.comment("Increases the Effectiveness of your Stand's Moves (Default: 80)").define("Precision", (double) 80);
		SILVERCHARIOTPOTENTIAL = BUILDER.comment("Allows your Stand to Acquire More Moves and EXP (Default: 60)").define("Potential", (double) 60);
		BUILDER.pop();
		BUILDER.push("Hermit Purple");
		HERMITPURPLESTRENGTH = BUILDER.comment("Increases the Power of your Stand's Moves (Default: 40)").define("Strength", (double) 40);
		HERMITPURPLEDURABILITY = BUILDER.comment("Increases your Health, and Decreases Damage Taken (Default: 100)").define("Durability", (double) 100);
		HERMITPURPLEPRECISION = BUILDER.comment("Increases the Effectiveness of your Stand's Moves (Default: 40)").define("Precision", (double) 40);
		HERMITPURPLEPOTENTIAL = BUILDER.comment("Allows your Stand to Acquire More Moves and EXP (Default: 20)").define("Potential", (double) 20);
		BUILDER.pop();
		BUILDER.push("The Fool");
		THEFOOLSTRENGTH = BUILDER.comment("Increases the Power of your Stand's Moves (Default: 80)").define("Strength", (double) 80);
		THEFOOLDURABILITY = BUILDER.comment("Increases your Health, and Decreases Damage Taken (Default: 60)").define("Durability", (double) 60);
		THEFOOLPRECISION = BUILDER.comment("Increases the Effectiveness of your Stand's Moves (Default: 40)").define("Precision", (double) 40);
		THEFOOLPOTENTIAL = BUILDER.comment("Allows your Stand to Acquire More Moves and EXP (Default: 60)").define("Potential", (double) 60);
		BUILDER.pop();
		BUILDER.push("The World");
		THEWORLDSTRENGTH = BUILDER.comment("Increases the Power of your Stand's Moves (Default: 100)").define("Strength", (double) 100);
		THEWORLDDURABILITY = BUILDER.comment("Increases your Health, and Decreases Damage Taken (Default: 100)").define("Durability", (double) 100);
		THEWORLDPRECISION = BUILDER.comment("Increases the Effectiveness of your Stand's Moves (Default: 80)").define("Precision", (double) 80);
		THEWORLDPOTENTIAL = BUILDER.comment("Allows your Stand to Acquire More Moves and EXP (Default: 80)").define("Potential", (double) 80);
		BUILDER.pop();

		SPEC = BUILDER.build();
	}

}
