
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.jojowos.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.ArmorItem;

import net.mcreator.jojowos.item.TheWorldDiscItem;
import net.mcreator.jojowos.item.TheHandDiscItem;
import net.mcreator.jojowos.item.TheFoolDiscItem;
import net.mcreator.jojowos.item.StoneArrowItem;
import net.mcreator.jojowos.item.StardustArrowItem;
import net.mcreator.jojowos.item.StarPlatinumDiscItem;
import net.mcreator.jojowos.item.StandArrowItem;
import net.mcreator.jojowos.item.SilverChariotDiscItem;
import net.mcreator.jojowos.item.ShinyArrowItem;
import net.mcreator.jojowos.item.RequiemArrowItem;
import net.mcreator.jojowos.item.RedCapeItem;
import net.mcreator.jojowos.item.PolnareffClothesItem;
import net.mcreator.jojowos.item.PolaroidItem;
import net.mcreator.jojowos.item.OldJosephClothesItem;
import net.mcreator.jojowos.item.MeteoriteBarItem;
import net.mcreator.jojowos.item.MagiciansRedDiscItem;
import net.mcreator.jojowos.item.LoveDeluxeDiscItem;
import net.mcreator.jojowos.item.LegendaryArrowItem;
import net.mcreator.jojowos.item.KillerQueenDiscItem;
import net.mcreator.jojowos.item.KakyoinClothesItem;
import net.mcreator.jojowos.item.JotaroKujoP3ClothesItem;
import net.mcreator.jojowos.item.HierophantSeroPlayerItem;
import net.mcreator.jojowos.item.HierophantGreenPilotOVAItem;
import net.mcreator.jojowos.item.HierophantGreenPilotMangaItem;
import net.mcreator.jojowos.item.HierophantGreenPilotBlueItem;
import net.mcreator.jojowos.item.HierophantGreenPilotAnimeItem;
import net.mcreator.jojowos.item.HierophantGreenDiscItem;
import net.mcreator.jojowos.item.HermitRedItem;
import net.mcreator.jojowos.item.HermitPurpleVenomItem;
import net.mcreator.jojowos.item.HermitPurplePart4Item;
import net.mcreator.jojowos.item.HermitPurpleNeroItem;
import net.mcreator.jojowos.item.HermitPurpleMangaItem;
import net.mcreator.jojowos.item.HermitPurpleLuckItem;
import net.mcreator.jojowos.item.HermitPurpleLinkItem;
import net.mcreator.jojowos.item.HermitPurpleItem;
import net.mcreator.jojowos.item.HermitPurpleGiganteItem;
import net.mcreator.jojowos.item.HermitPurpleDiscItem;
import net.mcreator.jojowos.item.HermitPurpleAutomailItem;
import net.mcreator.jojowos.item.HermitGoldItem;
import net.mcreator.jojowos.item.HermitBlueItem;
import net.mcreator.jojowos.item.HeavensDoorDiscItem;
import net.mcreator.jojowos.item.HarvestDiscItem;
import net.mcreator.jojowos.item.GoldenArrowItem;
import net.mcreator.jojowos.item.EmptyStandDiscItem;
import net.mcreator.jojowos.item.EmptyArmorItem;
import net.mcreator.jojowos.item.EchoesAct3DiscItem;
import net.mcreator.jojowos.item.EchoesAct2DiscItem;
import net.mcreator.jojowos.item.EchoesAct1DiscItem;
import net.mcreator.jojowos.item.EchoesAct0DiscItem;
import net.mcreator.jojowos.item.DioTopItem;
import net.mcreator.jojowos.item.DioClothesItem;
import net.mcreator.jojowos.item.DioCapeItem;
import net.mcreator.jojowos.item.DiamondArrowItem;
import net.mcreator.jojowos.item.CrazyDiamondDiscItem;
import net.mcreator.jojowos.item.CoffeeGumItem;
import net.mcreator.jojowos.item.ChiliPeppersDiscItem;
import net.mcreator.jojowos.item.CameraItem;
import net.mcreator.jojowos.item.AvdolClothesItem;
import net.mcreator.jojowos.item.AncientBowItem;
import net.mcreator.jojowos.item.AchievementTheWorldItem;
import net.mcreator.jojowos.item.AchievementTheFoolItem;
import net.mcreator.jojowos.item.AchievementSwordLaunchItem;
import net.mcreator.jojowos.item.AchievementStarPlatinumItem;
import net.mcreator.jojowos.item.AchievementStarFingerItem;
import net.mcreator.jojowos.item.AchievementSilverChariotItem;
import net.mcreator.jojowos.item.AchievementRoadRollerItem;
import net.mcreator.jojowos.item.AchievementMagiciansRedItem;
import net.mcreator.jojowos.item.AchievementKnifeTossItem;
import net.mcreator.jojowos.item.AchievementHierophantGreenItem;
import net.mcreator.jojowos.item.AchievementHermitPurpleItem;
import net.mcreator.jojowos.item.AchievementCrossfireSpecialItem;
import net.mcreator.jojowos.item.AchievementBearingShotItem;
import net.mcreator.jojowos.item.Achievement20MeterEmeraldItem;
import net.mcreator.jojowos.JojowosMod;

public class JojowosModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, JojowosMod.MODID);
	public static final RegistryObject<Item> STAND_ARROW = REGISTRY.register("stand_arrow", () -> new StandArrowItem());
	public static final RegistryObject<Item> STARDUST_ARROW = REGISTRY.register("stardust_arrow", () -> new StardustArrowItem());
	public static final RegistryObject<Item> DIAMOND_ARROW = REGISTRY.register("diamond_arrow", () -> new DiamondArrowItem());
	public static final RegistryObject<Item> GOLDEN_ARROW = REGISTRY.register("golden_arrow", () -> new GoldenArrowItem());
	public static final RegistryObject<Item> STONE_ARROW = REGISTRY.register("stone_arrow", () -> new StoneArrowItem());
	public static final RegistryObject<Item> REQUIEM_ARROW = REGISTRY.register("requiem_arrow", () -> new RequiemArrowItem());
	public static final RegistryObject<Item> HERMIT_PURPLE = REGISTRY.register("hermit_purple", () -> new HermitPurpleItem());
	public static final RegistryObject<Item> HERMIT_PURPLE_PART_4 = REGISTRY.register("hermit_purple_part_4", () -> new HermitPurplePart4Item());
	public static final RegistryObject<Item> HERMIT_PURPLE_MANGA = REGISTRY.register("hermit_purple_manga", () -> new HermitPurpleMangaItem());
	public static final RegistryObject<Item> HERMIT_RED = REGISTRY.register("hermit_red", () -> new HermitRedItem());
	public static final RegistryObject<Item> HERMIT_BLUE = REGISTRY.register("hermit_blue", () -> new HermitBlueItem());
	public static final RegistryObject<Item> HERMIT_GOLD = REGISTRY.register("hermit_gold", () -> new HermitGoldItem());
	public static final RegistryObject<Item> CAMERA = REGISTRY.register("camera", () -> new CameraItem());
	public static final RegistryObject<Item> POLAROID = REGISTRY.register("polaroid", () -> new PolaroidItem());
	public static final RegistryObject<Item> SHINY_ARROW = REGISTRY.register("shiny_arrow", () -> new ShinyArrowItem());
	public static final RegistryObject<Item> EMPTY_STAND_DISC = REGISTRY.register("empty_stand_disc", () -> new EmptyStandDiscItem());
	public static final RegistryObject<Item> STAR_PLATINUM_DISC = REGISTRY.register("star_platinum_disc", () -> new StarPlatinumDiscItem());
	public static final RegistryObject<Item> HIEROPHANT_GREEN_DISC = REGISTRY.register("hierophant_green_disc", () -> new HierophantGreenDiscItem());
	public static final RegistryObject<Item> MAGICIANS_RED_DISC = REGISTRY.register("magicians_red_disc", () -> new MagiciansRedDiscItem());
	public static final RegistryObject<Item> SILVER_CHARIOT_DISC = REGISTRY.register("silver_chariot_disc", () -> new SilverChariotDiscItem());
	public static final RegistryObject<Item> HERMIT_PURPLE_DISC = REGISTRY.register("hermit_purple_disc", () -> new HermitPurpleDiscItem());
	public static final RegistryObject<Item> METEORITE_ORE = block(JojowosModBlocks.METEORITE_ORE);
	public static final RegistryObject<Item> METEORITE_BAR = REGISTRY.register("meteorite_bar", () -> new MeteoriteBarItem());
	public static final RegistryObject<Item> THE_WORLD_DISC = REGISTRY.register("the_world_disc", () -> new TheWorldDiscItem());
	public static final RegistryObject<Item> THE_FOOL_DISC = REGISTRY.register("the_fool_disc", () -> new TheFoolDiscItem());
	public static final RegistryObject<Item> HARDENED_SAND = block(JojowosModBlocks.HARDENED_SAND);
	public static final RegistryObject<Item> EMPTY_ARMOR_HELMET = REGISTRY.register("empty_armor_helmet", () -> new EmptyArmorItem.Helmet());
	public static final RegistryObject<Item> EMPTY_ARMOR_CHESTPLATE = REGISTRY.register("empty_armor_chestplate", () -> new EmptyArmorItem.Chestplate());
	public static final RegistryObject<Item> EMPTY_ARMOR_LEGGINGS = REGISTRY.register("empty_armor_leggings", () -> new EmptyArmorItem.Leggings());
	public static final RegistryObject<Item> EMPTY_ARMOR_BOOTS = REGISTRY.register("empty_armor_boots", () -> new EmptyArmorItem.Boots());
	public static final RegistryObject<Item> ACHIEVEMENT_HERMIT_PURPLE = REGISTRY.register("achievement_hermit_purple", () -> new AchievementHermitPurpleItem());
	public static final RegistryObject<Item> ACHIEVEMENT_STAR_PLATINUM = REGISTRY.register("achievement_star_platinum", () -> new AchievementStarPlatinumItem());
	public static final RegistryObject<Item> ACHIEVEMENT_HIEROPHANT_GREEN = REGISTRY.register("achievement_hierophant_green", () -> new AchievementHierophantGreenItem());
	public static final RegistryObject<Item> ACHIEVEMENT_MAGICIANS_RED = REGISTRY.register("achievement_magicians_red", () -> new AchievementMagiciansRedItem());
	public static final RegistryObject<Item> ACHIEVEMENT_SILVER_CHARIOT = REGISTRY.register("achievement_silver_chariot", () -> new AchievementSilverChariotItem());
	public static final RegistryObject<Item> ACHIEVEMENT_THE_FOOL = REGISTRY.register("achievement_the_fool", () -> new AchievementTheFoolItem());
	public static final RegistryObject<Item> ACHIEVEMENT_THE_WORLD = REGISTRY.register("achievement_the_world", () -> new AchievementTheWorldItem());
	public static final RegistryObject<Item> JOTARO_KUJO_P_3_CLOTHES_HELMET = REGISTRY.register("jotaro_kujo_p_3_clothes_helmet", () -> new JotaroKujoP3ClothesItem.Helmet());
	public static final RegistryObject<Item> JOTARO_KUJO_P_3_CLOTHES_CHESTPLATE = REGISTRY.register("jotaro_kujo_p_3_clothes_chestplate", () -> new JotaroKujoP3ClothesItem.Chestplate());
	public static final RegistryObject<Item> JOTARO_KUJO_P_3_CLOTHES_LEGGINGS = REGISTRY.register("jotaro_kujo_p_3_clothes_leggings", () -> new JotaroKujoP3ClothesItem.Leggings());
	public static final RegistryObject<Item> JOTARO_KUJO_P_3_CLOTHES_BOOTS = REGISTRY.register("jotaro_kujo_p_3_clothes_boots", () -> new JotaroKujoP3ClothesItem.Boots());
	public static final RegistryObject<Item> JOTARO_KUJO_PART_3_SPAWN_EGG = REGISTRY.register("jotaro_kujo_part_3_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.JOTARO_KUJO_PART_3, -12041414, -7037, new Item.Properties()));
	public static final RegistryObject<Item> ACHIEVEMENT_STAR_FINGER = REGISTRY.register("achievement_star_finger", () -> new AchievementStarFingerItem());
	public static final RegistryObject<Item> ACHIEVEMENT_BEARING_SHOT = REGISTRY.register("achievement_bearing_shot", () -> new AchievementBearingShotItem());
	public static final RegistryObject<Item> ACHIEVEMENT_KNIFE_TOSS = REGISTRY.register("achievement_knife_toss", () -> new AchievementKnifeTossItem());
	public static final RegistryObject<Item> ACHIEVEMENT_ROAD_ROLLER = REGISTRY.register("achievement_road_roller", () -> new AchievementRoadRollerItem());
	public static final RegistryObject<Item> ACHIEVEMENT_CROSSFIRE_SPECIAL = REGISTRY.register("achievement_crossfire_special", () -> new AchievementCrossfireSpecialItem());
	public static final RegistryObject<Item> DIO_CLOTHES_HELMET = REGISTRY.register("dio_clothes_helmet", () -> new DioClothesItem.Helmet());
	public static final RegistryObject<Item> DIO_CLOTHES_CHESTPLATE = REGISTRY.register("dio_clothes_chestplate", () -> new DioClothesItem.Chestplate());
	public static final RegistryObject<Item> DIO_CLOTHES_LEGGINGS = REGISTRY.register("dio_clothes_leggings", () -> new DioClothesItem.Leggings());
	public static final RegistryObject<Item> DIO_CLOTHES_BOOTS = REGISTRY.register("dio_clothes_boots", () -> new DioClothesItem.Boots());
	public static final RegistryObject<Item> DIO_CAPE_CHESTPLATE = REGISTRY.register("dio_cape_chestplate", () -> new DioCapeItem.Chestplate());
	public static final RegistryObject<Item> DIO_TOP_CHESTPLATE = REGISTRY.register("dio_top_chestplate", () -> new DioTopItem.Chestplate());
	public static final RegistryObject<Item> DIO_SPAWN_EGG = REGISTRY.register("dio_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.DIO, -2706327, -9526435, new Item.Properties()));
	public static final RegistryObject<Item> DIO_CAPED_SPAWN_EGG = REGISTRY.register("dio_caped_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.DIO_CAPED, -8447954, -2706327, new Item.Properties()));
	public static final RegistryObject<Item> DIO_AWAKENED_SPAWN_EGG = REGISTRY.register("dio_awakened_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.DIO_AWAKENED, -4683440, -12418751, new Item.Properties()));
	public static final RegistryObject<Item> IGGY_SPAWN_EGG = REGISTRY.register("iggy_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.IGGY, -15000546, -263176, new Item.Properties()));
	public static final RegistryObject<Item> OLD_JOSEPH_JOESTAR_SPAWN_EGG = REGISTRY.register("old_joseph_joestar_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.OLD_JOSEPH_JOESTAR, -1843793, -6191275, new Item.Properties()));
	public static final RegistryObject<Item> OLD_JOSEPH_CLOTHES_HELMET = REGISTRY.register("old_joseph_clothes_helmet", () -> new OldJosephClothesItem.Helmet());
	public static final RegistryObject<Item> OLD_JOSEPH_CLOTHES_CHESTPLATE = REGISTRY.register("old_joseph_clothes_chestplate", () -> new OldJosephClothesItem.Chestplate());
	public static final RegistryObject<Item> OLD_JOSEPH_CLOTHES_LEGGINGS = REGISTRY.register("old_joseph_clothes_leggings", () -> new OldJosephClothesItem.Leggings());
	public static final RegistryObject<Item> OLD_JOSEPH_CLOTHES_BOOTS = REGISTRY.register("old_joseph_clothes_boots", () -> new OldJosephClothesItem.Boots());
	public static final RegistryObject<Item> JEAN_PIERRE_POLNAREFF_SPAWN_EGG = REGISTRY.register("jean_pierre_polnareff_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.JEAN_PIERRE_POLNAREFF, -6440774, -15788773, new Item.Properties()));
	public static final RegistryObject<Item> POLNAREFF_CLOTHES_HELMET = REGISTRY.register("polnareff_clothes_helmet", () -> new PolnareffClothesItem.Helmet());
	public static final RegistryObject<Item> POLNAREFF_CLOTHES_CHESTPLATE = REGISTRY.register("polnareff_clothes_chestplate", () -> new PolnareffClothesItem.Chestplate());
	public static final RegistryObject<Item> POLNAREFF_CLOTHES_LEGGINGS = REGISTRY.register("polnareff_clothes_leggings", () -> new PolnareffClothesItem.Leggings());
	public static final RegistryObject<Item> POLNAREFF_CLOTHES_BOOTS = REGISTRY.register("polnareff_clothes_boots", () -> new PolnareffClothesItem.Boots());
	public static final RegistryObject<Item> ACHIEVEMENT_20_METER_EMERALD = REGISTRY.register("achievement_20_meter_emerald", () -> new Achievement20MeterEmeraldItem());
	public static final RegistryObject<Item> ACHIEVEMENT_SWORD_LAUNCH = REGISTRY.register("achievement_sword_launch", () -> new AchievementSwordLaunchItem());
	public static final RegistryObject<Item> LEGENDARY_ARROW = REGISTRY.register("legendary_arrow", () -> new LegendaryArrowItem());
	public static final RegistryObject<Item> KAKYOIN_CLOTHES_HELMET = REGISTRY.register("kakyoin_clothes_helmet", () -> new KakyoinClothesItem.Helmet());
	public static final RegistryObject<Item> KAKYOIN_CLOTHES_CHESTPLATE = REGISTRY.register("kakyoin_clothes_chestplate", () -> new KakyoinClothesItem.Chestplate());
	public static final RegistryObject<Item> KAKYOIN_CLOTHES_LEGGINGS = REGISTRY.register("kakyoin_clothes_leggings", () -> new KakyoinClothesItem.Leggings());
	public static final RegistryObject<Item> KAKYOIN_CLOTHES_BOOTS = REGISTRY.register("kakyoin_clothes_boots", () -> new KakyoinClothesItem.Boots());
	public static final RegistryObject<Item> NORIAKI_KAKYOIN_SPAWN_EGG = REGISTRY.register("noriaki_kakyoin_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.NORIAKI_KAKYOIN, -12364231, -3576220, new Item.Properties()));
	public static final RegistryObject<Item> AVDOL_CLOTHES_HELMET = REGISTRY.register("avdol_clothes_helmet", () -> new AvdolClothesItem.Helmet());
	public static final RegistryObject<Item> AVDOL_CLOTHES_CHESTPLATE = REGISTRY.register("avdol_clothes_chestplate", () -> new AvdolClothesItem.Chestplate());
	public static final RegistryObject<Item> AVDOL_CLOTHES_LEGGINGS = REGISTRY.register("avdol_clothes_leggings", () -> new AvdolClothesItem.Leggings());
	public static final RegistryObject<Item> AVDOL_CLOTHES_BOOTS = REGISTRY.register("avdol_clothes_boots", () -> new AvdolClothesItem.Boots());
	public static final RegistryObject<Item> MUHAMMED_AVDOL_SPAWN_EGG = REGISTRY.register("muhammed_avdol_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.MUHAMMED_AVDOL, -6862282, -3172297, new Item.Properties()));
	public static final RegistryObject<Item> COFFEE_GUM = REGISTRY.register("coffee_gum", () -> new CoffeeGumItem());
	public static final RegistryObject<Item> ANCIENT_BOW = REGISTRY.register("ancient_bow", () -> new AncientBowItem());
	public static final RegistryObject<HierophantGreenPilotAnimeItem> HIEROPHANT_GREEN_PILOT_ANIME_CHESTPLATE = REGISTRY.register("hierophant_green_pilot_anime_chestplate",
			() -> new HierophantGreenPilotAnimeItem(ArmorItem.Type.CHESTPLATE, new Item.Properties()));
	public static final RegistryObject<HierophantGreenPilotMangaItem> HIEROPHANT_GREEN_PILOT_MANGA_CHESTPLATE = REGISTRY.register("hierophant_green_pilot_manga_chestplate",
			() -> new HierophantGreenPilotMangaItem(ArmorItem.Type.CHESTPLATE, new Item.Properties()));
	public static final RegistryObject<HierophantGreenPilotOVAItem> HIEROPHANT_GREEN_PILOT_OVA_CHESTPLATE = REGISTRY.register("hierophant_green_pilot_ova_chestplate",
			() -> new HierophantGreenPilotOVAItem(ArmorItem.Type.CHESTPLATE, new Item.Properties()));
	public static final RegistryObject<HierophantGreenPilotBlueItem> HIEROPHANT_GREEN_PILOT_BLUE_CHESTPLATE = REGISTRY.register("hierophant_green_pilot_blue_chestplate",
			() -> new HierophantGreenPilotBlueItem(ArmorItem.Type.CHESTPLATE, new Item.Properties()));
	public static final RegistryObject<Item> RED_CAPE_CHESTPLATE = REGISTRY.register("red_cape_chestplate", () -> new RedCapeItem.Chestplate());
	public static final RegistryObject<Item> HERMIT_PURPLE_AUTOMAIL = REGISTRY.register("hermit_purple_automail", () -> new HermitPurpleAutomailItem());
	public static final RegistryObject<Item> CRAZY_DIAMOND_DISC = REGISTRY.register("crazy_diamond_disc", () -> new CrazyDiamondDiscItem());
	public static final RegistryObject<Item> THE_HAND_DISC = REGISTRY.register("the_hand_disc", () -> new TheHandDiscItem());
	public static final RegistryObject<Item> HEAVENS_DOOR_DISC = REGISTRY.register("heavens_door_disc", () -> new HeavensDoorDiscItem());
	public static final RegistryObject<Item> HARVEST_DISC = REGISTRY.register("harvest_disc", () -> new HarvestDiscItem());
	public static final RegistryObject<Item> KILLER_QUEEN_DISC = REGISTRY.register("killer_queen_disc", () -> new KillerQueenDiscItem());
	public static final RegistryObject<Item> ECHOES_ACT_0_DISC = REGISTRY.register("echoes_act_0_disc", () -> new EchoesAct0DiscItem());
	public static final RegistryObject<Item> ECHOES_ACT_1_DISC = REGISTRY.register("echoes_act_1_disc", () -> new EchoesAct1DiscItem());
	public static final RegistryObject<Item> ECHOES_ACT_2_DISC = REGISTRY.register("echoes_act_2_disc", () -> new EchoesAct2DiscItem());
	public static final RegistryObject<Item> ECHOES_ACT_3_DISC = REGISTRY.register("echoes_act_3_disc", () -> new EchoesAct3DiscItem());
	public static final RegistryObject<Item> CHILI_PEPPERS_DISC = REGISTRY.register("chili_peppers_disc", () -> new ChiliPeppersDiscItem());
	public static final RegistryObject<Item> LOVE_DELUXE_DISC = REGISTRY.register("love_deluxe_disc", () -> new LoveDeluxeDiscItem());
	public static final RegistryObject<Item> HERMIT_PURPLE_GIGANTE = REGISTRY.register("hermit_purple_gigante", () -> new HermitPurpleGiganteItem());
	public static final RegistryObject<Item> HERMIT_PURPLE_VENOM = REGISTRY.register("hermit_purple_venom", () -> new HermitPurpleVenomItem());
	public static final RegistryObject<Item> HERMIT_PURPLE_LINK = REGISTRY.register("hermit_purple_link", () -> new HermitPurpleLinkItem());
	public static final RegistryObject<Item> HERMIT_PURPLE_NERO = REGISTRY.register("hermit_purple_nero", () -> new HermitPurpleNeroItem());
	public static final RegistryObject<Item> HERMIT_PURPLE_LUCK = REGISTRY.register("hermit_purple_luck", () -> new HermitPurpleLuckItem());
	public static final RegistryObject<HierophantSeroPlayerItem> HIEROPHANT_SERO_PLAYER_CHESTPLATE = REGISTRY.register("hierophant_sero_player_chestplate", () -> new HierophantSeroPlayerItem(ArmorItem.Type.CHESTPLATE, new Item.Properties()));

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
