
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.jojowos.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.ArmorItem;

import net.mcreator.jojowos.item.TheWorldDiscItem;
import net.mcreator.jojowos.item.TheFoolDiscItem;
import net.mcreator.jojowos.item.StoneArrowItem;
import net.mcreator.jojowos.item.StardustArrowItem;
import net.mcreator.jojowos.item.StarPlatinumDiscItem;
import net.mcreator.jojowos.item.StandArrowItem;
import net.mcreator.jojowos.item.SilverChariotDiscItem;
import net.mcreator.jojowos.item.ShinyArrowItem;
import net.mcreator.jojowos.item.RequiemArrowItem;
import net.mcreator.jojowos.item.RedCapeItem;
import net.mcreator.jojowos.item.PolnareffClothesItem;
import net.mcreator.jojowos.item.PolaroidItem;
import net.mcreator.jojowos.item.OldJosephClothesItem;
import net.mcreator.jojowos.item.MeteoriteBarItem;
import net.mcreator.jojowos.item.MagiciansRedDiscItem;
import net.mcreator.jojowos.item.LegendaryArrowItem;
import net.mcreator.jojowos.item.KakyoinClothesItem;
import net.mcreator.jojowos.item.JotaroKujoP3ClothesItem;
import net.mcreator.jojowos.item.HierophantGreenPilotOVAItem;
import net.mcreator.jojowos.item.HierophantGreenPilotMangaItem;
import net.mcreator.jojowos.item.HierophantGreenPilotBlueItem;
import net.mcreator.jojowos.item.HierophantGreenPilotAnimeItem;
import net.mcreator.jojowos.item.HierophantGreenDiscItem;
import net.mcreator.jojowos.item.HermitRedItem;
import net.mcreator.jojowos.item.HermitPurplePart4Item;
import net.mcreator.jojowos.item.HermitPurpleMangaItem;
import net.mcreator.jojowos.item.HermitPurpleItem;
import net.mcreator.jojowos.item.HermitPurpleDiscItem;
import net.mcreator.jojowos.item.HermitPurpleAutomailItem;
import net.mcreator.jojowos.item.HermitGoldItem;
import net.mcreator.jojowos.item.HermitBlueItem;
import net.mcreator.jojowos.item.GoldenArrowItem;
import net.mcreator.jojowos.item.EmptyStandDiscItem;
import net.mcreator.jojowos.item.EmptyArmorItem;
import net.mcreator.jojowos.item.DioTopItem;
import net.mcreator.jojowos.item.DioClothesItem;
import net.mcreator.jojowos.item.DioCapeItem;
import net.mcreator.jojowos.item.DiamondArrowItem;
import net.mcreator.jojowos.item.CoffeeGumItem;
import net.mcreator.jojowos.item.CameraItem;
import net.mcreator.jojowos.item.AvdolClothesItem;
import net.mcreator.jojowos.item.AncientBowItem;
import net.mcreator.jojowos.item.AchievementWorldTimeStopItem;
import net.mcreator.jojowos.item.AchievementWorldTimeSkipItem;
import net.mcreator.jojowos.item.AchievementTheWorldItem;
import net.mcreator.jojowos.item.AchievementTheFoolItem;
import net.mcreator.jojowos.item.AchievementSwordLaunchItem;
import net.mcreator.jojowos.item.AchievementStarTimeStopItem;
import net.mcreator.jojowos.item.AchievementStarTimeSkipItem;
import net.mcreator.jojowos.item.AchievementStarPlatinumItem;
import net.mcreator.jojowos.item.AchievementStarFingerItem;
import net.mcreator.jojowos.item.AchievementSilverChariotItem;
import net.mcreator.jojowos.item.AchievementSandGliderItem;
import net.mcreator.jojowos.item.AchievementSandDomeItem;
import net.mcreator.jojowos.item.AchievementRoadRollerItem;
import net.mcreator.jojowos.item.AchievementRedBindItem;
import net.mcreator.jojowos.item.AchievementMudaKickItem;
import net.mcreator.jojowos.item.AchievementMagiciansRedItem;
import net.mcreator.jojowos.item.AchievementLifeDetectItem;
import net.mcreator.jojowos.item.AchievementKnifeTossItem;
import net.mcreator.jojowos.item.AchievementInhaleItem;
import net.mcreator.jojowos.item.AchievementHierophantGreenItem;
import net.mcreator.jojowos.item.AchievementHieroGrappleItem;
import net.mcreator.jojowos.item.AchievementHermitTangleItem;
import net.mcreator.jojowos.item.AchievementHermitPurpleItem;
import net.mcreator.jojowos.item.AchievementHermitCameraItem;
import net.mcreator.jojowos.item.AchievementCrossfireSpecialItem;
import net.mcreator.jojowos.item.AchievementBodyControlItem;
import net.mcreator.jojowos.item.AchievementBladeCycloneItem;
import net.mcreator.jojowos.item.AchievementBearingShotItem;
import net.mcreator.jojowos.item.AchievementArmorOffItem;
import net.mcreator.jojowos.item.Achievement20MeterEmeraldItem;
import net.mcreator.jojowos.JojowosMod;

public class JojowosModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, JojowosMod.MODID);
	public static final RegistryObject<Item> METEORITE_ORE = block(JojowosModBlocks.METEORITE_ORE);
	public static final RegistryObject<Item> METEORITE_BAR = REGISTRY.register("meteorite_bar", () -> new MeteoriteBarItem());
	public static final RegistryObject<Item> STAND_ARROW = REGISTRY.register("stand_arrow", () -> new StandArrowItem());
	public static final RegistryObject<Item> SHINY_ARROW = REGISTRY.register("shiny_arrow", () -> new ShinyArrowItem());
	public static final RegistryObject<Item> CAMERA = REGISTRY.register("camera", () -> new CameraItem());
	public static final RegistryObject<Item> COFFEE_GUM = REGISTRY.register("coffee_gum", () -> new CoffeeGumItem());
	public static final RegistryObject<Item> ANCIENT_BOW = REGISTRY.register("ancient_bow", () -> new AncientBowItem());
	public static final RegistryObject<Item> EMPTY_STAND_DISC = REGISTRY.register("empty_stand_disc", () -> new EmptyStandDiscItem());
	public static final RegistryObject<Item> STAR_PLATINUM_DISC = REGISTRY.register("star_platinum_disc", () -> new StarPlatinumDiscItem());
	public static final RegistryObject<Item> HIEROPHANT_GREEN_DISC = REGISTRY.register("hierophant_green_disc", () -> new HierophantGreenDiscItem());
	public static final RegistryObject<Item> MAGICIANS_RED_DISC = REGISTRY.register("magicians_red_disc", () -> new MagiciansRedDiscItem());
	public static final RegistryObject<Item> SILVER_CHARIOT_DISC = REGISTRY.register("silver_chariot_disc", () -> new SilverChariotDiscItem());
	public static final RegistryObject<Item> HERMIT_PURPLE_DISC = REGISTRY.register("hermit_purple_disc", () -> new HermitPurpleDiscItem());
	public static final RegistryObject<Item> THE_WORLD_DISC = REGISTRY.register("the_world_disc", () -> new TheWorldDiscItem());
	public static final RegistryObject<Item> THE_FOOL_DISC = REGISTRY.register("the_fool_disc", () -> new TheFoolDiscItem());
	public static final RegistryObject<Item> JOTARO_KUJO_P_3_CLOTHES_HELMET = REGISTRY.register("jotaro_kujo_p_3_clothes_helmet", () -> new JotaroKujoP3ClothesItem.Helmet());
	public static final RegistryObject<Item> JOTARO_KUJO_P_3_CLOTHES_CHESTPLATE = REGISTRY.register("jotaro_kujo_p_3_clothes_chestplate", () -> new JotaroKujoP3ClothesItem.Chestplate());
	public static final RegistryObject<Item> JOTARO_KUJO_P_3_CLOTHES_LEGGINGS = REGISTRY.register("jotaro_kujo_p_3_clothes_leggings", () -> new JotaroKujoP3ClothesItem.Leggings());
	public static final RegistryObject<Item> JOTARO_KUJO_P_3_CLOTHES_BOOTS = REGISTRY.register("jotaro_kujo_p_3_clothes_boots", () -> new JotaroKujoP3ClothesItem.Boots());
	public static final RegistryObject<Item> DIO_CLOTHES_HELMET = REGISTRY.register("dio_clothes_helmet", () -> new DioClothesItem.Helmet());
	public static final RegistryObject<Item> DIO_CLOTHES_CHESTPLATE = REGISTRY.register("dio_clothes_chestplate", () -> new DioClothesItem.Chestplate());
	public static final RegistryObject<Item> DIO_CLOTHES_LEGGINGS = REGISTRY.register("dio_clothes_leggings", () -> new DioClothesItem.Leggings());
	public static final RegistryObject<Item> DIO_CLOTHES_BOOTS = REGISTRY.register("dio_clothes_boots", () -> new DioClothesItem.Boots());
	public static final RegistryObject<Item> DIO_CAPE_CHESTPLATE = REGISTRY.register("dio_cape_chestplate", () -> new DioCapeItem.Chestplate());
	public static final RegistryObject<Item> RED_CAPE_CHESTPLATE = REGISTRY.register("red_cape_chestplate", () -> new RedCapeItem.Chestplate());
	public static final RegistryObject<Item> DIO_TOP_CHESTPLATE = REGISTRY.register("dio_top_chestplate", () -> new DioTopItem.Chestplate());
	public static final RegistryObject<Item> OLD_JOSEPH_CLOTHES_HELMET = REGISTRY.register("old_joseph_clothes_helmet", () -> new OldJosephClothesItem.Helmet());
	public static final RegistryObject<Item> OLD_JOSEPH_CLOTHES_CHESTPLATE = REGISTRY.register("old_joseph_clothes_chestplate", () -> new OldJosephClothesItem.Chestplate());
	public static final RegistryObject<Item> OLD_JOSEPH_CLOTHES_LEGGINGS = REGISTRY.register("old_joseph_clothes_leggings", () -> new OldJosephClothesItem.Leggings());
	public static final RegistryObject<Item> OLD_JOSEPH_CLOTHES_BOOTS = REGISTRY.register("old_joseph_clothes_boots", () -> new OldJosephClothesItem.Boots());
	public static final RegistryObject<Item> POLNAREFF_CLOTHES_HELMET = REGISTRY.register("polnareff_clothes_helmet", () -> new PolnareffClothesItem.Helmet());
	public static final RegistryObject<Item> POLNAREFF_CLOTHES_CHESTPLATE = REGISTRY.register("polnareff_clothes_chestplate", () -> new PolnareffClothesItem.Chestplate());
	public static final RegistryObject<Item> POLNAREFF_CLOTHES_LEGGINGS = REGISTRY.register("polnareff_clothes_leggings", () -> new PolnareffClothesItem.Leggings());
	public static final RegistryObject<Item> POLNAREFF_CLOTHES_BOOTS = REGISTRY.register("polnareff_clothes_boots", () -> new PolnareffClothesItem.Boots());
	public static final RegistryObject<Item> KAKYOIN_CLOTHES_HELMET = REGISTRY.register("kakyoin_clothes_helmet", () -> new KakyoinClothesItem.Helmet());
	public static final RegistryObject<Item> KAKYOIN_CLOTHES_CHESTPLATE = REGISTRY.register("kakyoin_clothes_chestplate", () -> new KakyoinClothesItem.Chestplate());
	public static final RegistryObject<Item> KAKYOIN_CLOTHES_LEGGINGS = REGISTRY.register("kakyoin_clothes_leggings", () -> new KakyoinClothesItem.Leggings());
	public static final RegistryObject<Item> KAKYOIN_CLOTHES_BOOTS = REGISTRY.register("kakyoin_clothes_boots", () -> new KakyoinClothesItem.Boots());
	public static final RegistryObject<Item> AVDOL_CLOTHES_HELMET = REGISTRY.register("avdol_clothes_helmet", () -> new AvdolClothesItem.Helmet());
	public static final RegistryObject<Item> AVDOL_CLOTHES_CHESTPLATE = REGISTRY.register("avdol_clothes_chestplate", () -> new AvdolClothesItem.Chestplate());
	public static final RegistryObject<Item> AVDOL_CLOTHES_LEGGINGS = REGISTRY.register("avdol_clothes_leggings", () -> new AvdolClothesItem.Leggings());
	public static final RegistryObject<Item> AVDOL_CLOTHES_BOOTS = REGISTRY.register("avdol_clothes_boots", () -> new AvdolClothesItem.Boots());
	public static final RegistryObject<Item> JOTARO_KUJO_PART_3_SPAWN_EGG = REGISTRY.register("jotaro_kujo_part_3_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.JOTARO_KUJO_PART_3, -12041414, -7037, new Item.Properties()));
	public static final RegistryObject<Item> DIO_CAPED_SPAWN_EGG = REGISTRY.register("dio_caped_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.DIO_CAPED, -8447954, -2706327, new Item.Properties()));
	public static final RegistryObject<Item> DIO_SPAWN_EGG = REGISTRY.register("dio_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.DIO, -2706327, -9526435, new Item.Properties()));
	public static final RegistryObject<Item> DIO_AWAKENED_SPAWN_EGG = REGISTRY.register("dio_awakened_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.DIO_AWAKENED, -4683440, -12418751, new Item.Properties()));
	public static final RegistryObject<Item> IGGY_SPAWN_EGG = REGISTRY.register("iggy_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.IGGY, -15000546, -263176, new Item.Properties()));
	public static final RegistryObject<Item> OLD_JOSEPH_JOESTAR_SPAWN_EGG = REGISTRY.register("old_joseph_joestar_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.OLD_JOSEPH_JOESTAR, -1843793, -6191275, new Item.Properties()));
	public static final RegistryObject<Item> JEAN_PIERRE_POLNAREFF_SPAWN_EGG = REGISTRY.register("jean_pierre_polnareff_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.JEAN_PIERRE_POLNAREFF, -6440774, -15788773, new Item.Properties()));
	public static final RegistryObject<Item> NORIAKI_KAKYOIN_SPAWN_EGG = REGISTRY.register("noriaki_kakyoin_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.NORIAKI_KAKYOIN, -12364231, -3576220, new Item.Properties()));
	public static final RegistryObject<Item> MUHAMMED_AVDOL_SPAWN_EGG = REGISTRY.register("muhammed_avdol_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.MUHAMMED_AVDOL, -6862282, -3172297, new Item.Properties()));
	public static final RegistryObject<Item> STAR_PLATINUM_P_3_SPAWN_EGG = REGISTRY.register("star_platinum_p_3_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.STAR_PLATINUM_P_3, -3407668, -10092442, new Item.Properties()));
	public static final RegistryObject<Item> STAR_PLATINUM_P_4_SPAWN_EGG = REGISTRY.register("star_platinum_p_4_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.STAR_PLATINUM_P_4, -3407668, -16711681, new Item.Properties()));
	public static final RegistryObject<Item> STAR_PLATINUM_P_6_SPAWN_EGG = REGISTRY.register("star_platinum_p_6_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.STAR_PLATINUM_P_6, -3407668, -6750055, new Item.Properties()));
	public static final RegistryObject<Item> STAR_PLATINUM_OVA_SPAWN_EGG = REGISTRY.register("star_platinum_ova_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.STAR_PLATINUM_OVA, -3355393, -16737844, new Item.Properties()));
	public static final RegistryObject<Item> STAR_PLATINUM_MANGA_SPAWN_EGG = REGISTRY.register("star_platinum_manga_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.STAR_PLATINUM_MANGA, -52225, -6749953, new Item.Properties()));
	public static final RegistryObject<Item> STAR_PLATINUM_BLUE_SPAWN_EGG = REGISTRY.register("star_platinum_blue_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.STAR_PLATINUM_BLUE, -16737793, -16763956, new Item.Properties()));
	public static final RegistryObject<Item> STAR_PLATINUM_GREEN_SPAWN_EGG = REGISTRY.register("star_platinum_green_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.STAR_PLATINUM_GREEN, -11822261, -14983106, new Item.Properties()));
	public static final RegistryObject<Item> MAGICIANS_RED_SPAWN_EGG = REGISTRY.register("magicians_red_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.MAGICIANS_RED, -26317, -52429, new Item.Properties()));
	public static final RegistryObject<Item> MAGICIANS_RED_MANGA_SPAWN_EGG = REGISTRY.register("magicians_red_manga_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.MAGICIANS_RED_MANGA, -26317, -52429, new Item.Properties()));
	public static final RegistryObject<Item> MAGICIANS_RED_OVA_SPAWN_EGG = REGISTRY.register("magicians_red_ova_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.MAGICIANS_RED_OVA, -52429, -6750208, new Item.Properties()));
	public static final RegistryObject<Item> MAGICIANS_RED_ASB_SPAWN_EGG = REGISTRY.register("magicians_red_asb_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.MAGICIANS_RED_ASB, -26317, -13421569, new Item.Properties()));
	public static final RegistryObject<Item> HIEROPHANT_GREEN_SPAWN_EGG = REGISTRY.register("hierophant_green_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.HIEROPHANT_GREEN, -16737997, -1, new Item.Properties()));
	public static final RegistryObject<Item> HIEROPHANT_GREEN_MANGA_SPAWN_EGG = REGISTRY.register("hierophant_green_manga_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.HIEROPHANT_GREEN_MANGA, -16751104, -3342388, new Item.Properties()));
	public static final RegistryObject<Item> HIEROPHANT_GREEN_OVA_SPAWN_EGG = REGISTRY.register("hierophant_green_ova_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.HIEROPHANT_GREEN_OVA, -16751104, -13210, new Item.Properties()));
	public static final RegistryObject<Item> HIEROPHANT_GREEN_BLUE_SPAWN_EGG = REGISTRY.register("hierophant_green_blue_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.HIEROPHANT_GREEN_BLUE, -10053121, -1, new Item.Properties()));
	public static final RegistryObject<Item> SILVER_CHARIOT_SPAWN_EGG = REGISTRY.register("silver_chariot_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.SILVER_CHARIOT, -1, -6710887, new Item.Properties()));
	public static final RegistryObject<Item> SILVER_CHARIOT_ARMORLESS_SPAWN_EGG = REGISTRY.register("silver_chariot_armorless_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.SILVER_CHARIOT_ARMORLESS, -1, -6710887, new Item.Properties()));
	public static final RegistryObject<Item> SILVER_CHARIOT_MANGA_SPAWN_EGG = REGISTRY.register("silver_chariot_manga_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.SILVER_CHARIOT_MANGA, -1, -6710887, new Item.Properties()));
	public static final RegistryObject<Item> SILVER_CHARIOT_MANGA_ARMORLESS_SPAWN_EGG = REGISTRY.register("silver_chariot_manga_armorless_spawn_egg",
			() -> new ForgeSpawnEggItem(JojowosModEntities.SILVER_CHARIOT_MANGA_ARMORLESS, -1, -6710887, new Item.Properties()));
	public static final RegistryObject<Item> SILVER_CHARIOT_GOLD_SPAWN_EGG = REGISTRY.register("silver_chariot_gold_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.SILVER_CHARIOT_GOLD, -154, -13261, new Item.Properties()));
	public static final RegistryObject<Item> SILVER_CHARIOT_GOLD_ARMORLESS_SPAWN_EGG = REGISTRY.register("silver_chariot_gold_armorless_spawn_egg",
			() -> new ForgeSpawnEggItem(JojowosModEntities.SILVER_CHARIOT_GOLD_ARMORLESS, -154, -13261, new Item.Properties()));
	public static final RegistryObject<Item> SILVER_CHARIOT_OVA_SPAWN_EGG = REGISTRY.register("silver_chariot_ova_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.SILVER_CHARIOT_OVA, -1, -26368, new Item.Properties()));
	public static final RegistryObject<Item> SILVER_CHARIOT_OVA_ARMORLESS_SPAWN_EGG = REGISTRY.register("silver_chariot_ova_armorless_spawn_egg",
			() -> new ForgeSpawnEggItem(JojowosModEntities.SILVER_CHARIOT_OVA_ARMORLESS, -1, -26368, new Item.Properties()));
	public static final RegistryObject<Item> STARDUST_ARROW = REGISTRY.register("stardust_arrow", () -> new StardustArrowItem());
	public static final RegistryObject<Item> DIAMOND_ARROW = REGISTRY.register("diamond_arrow", () -> new DiamondArrowItem());
	public static final RegistryObject<Item> GOLDEN_ARROW = REGISTRY.register("golden_arrow", () -> new GoldenArrowItem());
	public static final RegistryObject<Item> STONE_ARROW = REGISTRY.register("stone_arrow", () -> new StoneArrowItem());
	public static final RegistryObject<Item> REQUIEM_ARROW = REGISTRY.register("requiem_arrow", () -> new RequiemArrowItem());
	public static final RegistryObject<Item> HERMIT_PURPLE = REGISTRY.register("hermit_purple", () -> new HermitPurpleItem());
	public static final RegistryObject<Item> HERMIT_PURPLE_PART_4 = REGISTRY.register("hermit_purple_part_4", () -> new HermitPurplePart4Item());
	public static final RegistryObject<Item> HERMIT_PURPLE_MANGA = REGISTRY.register("hermit_purple_manga", () -> new HermitPurpleMangaItem());
	public static final RegistryObject<Item> HERMIT_RED = REGISTRY.register("hermit_red", () -> new HermitRedItem());
	public static final RegistryObject<Item> HERMIT_BLUE = REGISTRY.register("hermit_blue", () -> new HermitBlueItem());
	public static final RegistryObject<Item> HERMIT_GOLD = REGISTRY.register("hermit_gold", () -> new HermitGoldItem());
	public static final RegistryObject<Item> POLAROID = REGISTRY.register("polaroid", () -> new PolaroidItem());
	public static final RegistryObject<Item> MAGICIANS_GREEN_SPAWN_EGG = REGISTRY.register("magicians_green_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.MAGICIANS_GREEN, -3822216, -12663678, new Item.Properties()));
	public static final RegistryObject<Item> THE_WORLD_SPAWN_EGG = REGISTRY.register("the_world_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.THE_WORLD, -1327047, -8221572, new Item.Properties()));
	public static final RegistryObject<Item> THE_WORLD_SILVER_SPAWN_EGG = REGISTRY.register("the_world_silver_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.THE_WORLD_SILVER, -14145496, -10142836, new Item.Properties()));
	public static final RegistryObject<Item> THE_WORLD_MANGA_SPAWN_EGG = REGISTRY.register("the_world_manga_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.THE_WORLD_MANGA, -1316548, -1581151, new Item.Properties()));
	public static final RegistryObject<Item> THE_WORLD_OVA_SPAWN_EGG = REGISTRY.register("the_world_ova_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.THE_WORLD_OVA, -855639, -13287630, new Item.Properties()));
	public static final RegistryObject<Item> THE_WORLD_BLACK_SPAWN_EGG = REGISTRY.register("the_world_black_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.THE_WORLD_BLACK, -1774866, -12763581, new Item.Properties()));
	public static final RegistryObject<Item> THE_FOOL_SPAWN_EGG = REGISTRY.register("the_fool_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.THE_FOOL, -3618616, -14473944, new Item.Properties()));
	public static final RegistryObject<Item> THE_FOOL_OVA_SPAWN_EGG = REGISTRY.register("the_fool_ova_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.THE_FOOL_OVA, -8499391, -9150431, new Item.Properties()));
	public static final RegistryObject<Item> THE_FOOL_MANGA_SPAWN_EGG = REGISTRY.register("the_fool_manga_spawn_egg", () -> new ForgeSpawnEggItem(JojowosModEntities.THE_FOOL_MANGA, -3423177, -327884, new Item.Properties()));
	public static final RegistryObject<Item> HARDENED_SAND = block(JojowosModBlocks.HARDENED_SAND);
	public static final RegistryObject<Item> EMPTY_ARMOR_HELMET = REGISTRY.register("empty_armor_helmet", () -> new EmptyArmorItem.Helmet());
	public static final RegistryObject<Item> EMPTY_ARMOR_CHESTPLATE = REGISTRY.register("empty_armor_chestplate", () -> new EmptyArmorItem.Chestplate());
	public static final RegistryObject<Item> EMPTY_ARMOR_LEGGINGS = REGISTRY.register("empty_armor_leggings", () -> new EmptyArmorItem.Leggings());
	public static final RegistryObject<Item> EMPTY_ARMOR_BOOTS = REGISTRY.register("empty_armor_boots", () -> new EmptyArmorItem.Boots());
	public static final RegistryObject<Item> ACHIEVEMENT_HERMIT_CAMERA = REGISTRY.register("achievement_hermit_camera", () -> new AchievementHermitCameraItem());
	public static final RegistryObject<Item> ACHIEVEMENT_HERMIT_TANGLE = REGISTRY.register("achievement_hermit_tangle", () -> new AchievementHermitTangleItem());
	public static final RegistryObject<Item> ACHIEVEMENT_HERMIT_PURPLE = REGISTRY.register("achievement_hermit_purple", () -> new AchievementHermitPurpleItem());
	public static final RegistryObject<Item> ACHIEVEMENT_STAR_PLATINUM = REGISTRY.register("achievement_star_platinum", () -> new AchievementStarPlatinumItem());
	public static final RegistryObject<Item> ACHIEVEMENT_HIEROPHANT_GREEN = REGISTRY.register("achievement_hierophant_green", () -> new AchievementHierophantGreenItem());
	public static final RegistryObject<Item> ACHIEVEMENT_MAGICIANS_RED = REGISTRY.register("achievement_magicians_red", () -> new AchievementMagiciansRedItem());
	public static final RegistryObject<Item> ACHIEVEMENT_SILVER_CHARIOT = REGISTRY.register("achievement_silver_chariot", () -> new AchievementSilverChariotItem());
	public static final RegistryObject<Item> ACHIEVEMENT_THE_FOOL = REGISTRY.register("achievement_the_fool", () -> new AchievementTheFoolItem());
	public static final RegistryObject<Item> ACHIEVEMENT_THE_WORLD = REGISTRY.register("achievement_the_world", () -> new AchievementTheWorldItem());
	public static final RegistryObject<Item> ACHIEVEMENT_STAR_FINGER = REGISTRY.register("achievement_star_finger", () -> new AchievementStarFingerItem());
	public static final RegistryObject<Item> ACHIEVEMENT_INHALE = REGISTRY.register("achievement_inhale", () -> new AchievementInhaleItem());
	public static final RegistryObject<Item> ACHIEVEMENT_BEARING_SHOT = REGISTRY.register("achievement_bearing_shot", () -> new AchievementBearingShotItem());
	public static final RegistryObject<Item> ACHIEVEMENT_STAR_TIME_SKIP = REGISTRY.register("achievement_star_time_skip", () -> new AchievementStarTimeSkipItem());
	public static final RegistryObject<Item> ACHIEVEMENT_STAR_TIME_STOP = REGISTRY.register("achievement_star_time_stop", () -> new AchievementStarTimeStopItem());
	public static final RegistryObject<Item> ACHIEVEMENT_KNIFE_TOSS = REGISTRY.register("achievement_knife_toss", () -> new AchievementKnifeTossItem());
	public static final RegistryObject<Item> ACHIEVEMENT_MUDA_KICK = REGISTRY.register("achievement_muda_kick", () -> new AchievementMudaKickItem());
	public static final RegistryObject<Item> ACHIEVEMENT_WORLD_TIME_SKIP = REGISTRY.register("achievement_world_time_skip", () -> new AchievementWorldTimeSkipItem());
	public static final RegistryObject<Item> ACHIEVEMENT_WORLD_TIME_STOP = REGISTRY.register("achievement_world_time_stop", () -> new AchievementWorldTimeStopItem());
	public static final RegistryObject<Item> ACHIEVEMENT_ROAD_ROLLER = REGISTRY.register("achievement_road_roller", () -> new AchievementRoadRollerItem());
	public static final RegistryObject<Item> ACHIEVEMENT_CROSSFIRE_SPECIAL = REGISTRY.register("achievement_crossfire_special", () -> new AchievementCrossfireSpecialItem());
	public static final RegistryObject<Item> ACHIEVEMENT_RED_BIND = REGISTRY.register("achievement_red_bind", () -> new AchievementRedBindItem());
	public static final RegistryObject<Item> ACHIEVEMENT_LIFE_DETECT = REGISTRY.register("achievement_life_detect", () -> new AchievementLifeDetectItem());
	public static final RegistryObject<Item> ACHIEVEMENT_SAND_GLIDER = REGISTRY.register("achievement_sand_glider", () -> new AchievementSandGliderItem());
	public static final RegistryObject<Item> ACHIEVEMENT_SAND_DOME = REGISTRY.register("achievement_sand_dome", () -> new AchievementSandDomeItem());
	public static final RegistryObject<Item> ACHIEVEMENT_20_METER_EMERALD = REGISTRY.register("achievement_20_meter_emerald", () -> new Achievement20MeterEmeraldItem());
	public static final RegistryObject<Item> ACHIEVEMENT_HIERO_GRAPPLE = REGISTRY.register("achievement_hiero_grapple", () -> new AchievementHieroGrappleItem());
	public static final RegistryObject<Item> ACHIEVEMENT_BODY_CONTROL = REGISTRY.register("achievement_body_control", () -> new AchievementBodyControlItem());
	public static final RegistryObject<Item> ACHIEVEMENT_SWORD_LAUNCH = REGISTRY.register("achievement_sword_launch", () -> new AchievementSwordLaunchItem());
	public static final RegistryObject<Item> ACHIEVEMENT_BLADE_CYCLONE = REGISTRY.register("achievement_blade_cyclone", () -> new AchievementBladeCycloneItem());
	public static final RegistryObject<Item> ACHIEVEMENT_ARMOR_OFF = REGISTRY.register("achievement_armor_off", () -> new AchievementArmorOffItem());
	public static final RegistryObject<Item> LEGENDARY_ARROW = REGISTRY.register("legendary_arrow", () -> new LegendaryArrowItem());
	public static final RegistryObject<HierophantGreenPilotAnimeItem> HIEROPHANT_GREEN_PILOT_ANIME_CHESTPLATE = REGISTRY.register("hierophant_green_pilot_anime_chestplate",
			() -> new HierophantGreenPilotAnimeItem(ArmorItem.Type.CHESTPLATE, new Item.Properties()));
	public static final RegistryObject<HierophantGreenPilotMangaItem> HIEROPHANT_GREEN_PILOT_MANGA_CHESTPLATE = REGISTRY.register("hierophant_green_pilot_manga_chestplate",
			() -> new HierophantGreenPilotMangaItem(ArmorItem.Type.CHESTPLATE, new Item.Properties()));
	public static final RegistryObject<HierophantGreenPilotOVAItem> HIEROPHANT_GREEN_PILOT_OVA_CHESTPLATE = REGISTRY.register("hierophant_green_pilot_ova_chestplate",
			() -> new HierophantGreenPilotOVAItem(ArmorItem.Type.CHESTPLATE, new Item.Properties()));
	public static final RegistryObject<HierophantGreenPilotBlueItem> HIEROPHANT_GREEN_PILOT_BLUE_CHESTPLATE = REGISTRY.register("hierophant_green_pilot_blue_chestplate",
			() -> new HierophantGreenPilotBlueItem(ArmorItem.Type.CHESTPLATE, new Item.Properties()));
	public static final RegistryObject<Item> HERMIT_PURPLE_AUTOMAIL = REGISTRY.register("hermit_purple_automail", () -> new HermitPurpleAutomailItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
